# Generated by Django 3.2.19 on 2023-05-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='unit_2',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('sec', 'sec'), ('m', 'm')], default=None, max_length=40),
        ),
    ]
