# Generated by Django 3.2.19 on 2023-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_unit_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='unit_2',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('sec', 'sec'), ('m', 'm')], default='', max_length=40),
        ),
    ]
